const bancoPreguntas = [
    { categoria: "Secuencias Numéricas", pregunta: "¿Qué número continúa la serie? 2, 5, 10, 17, 26, ...", opciones: { A: "35", B: "37", C: "39", D: "41" }, correcta: "B", explicación: "La diferencia aumenta en números impares consecutivos: +3, +5, +7, +9, toca +11 (26+11=37)." },
    { categoria: "Secuencias Numéricas", pregunta: "Complete la secuencia faltante: 3, 9, 27, 81, ...", opciones: { A: "162", B: "243", C: "120", D: "324" }, correcta: "B", explicación: "Progresión geométrica donde cada término se multiplica por 3 (81 * 3 = 243)." },
    { categoria: "Secuencias Numéricas", pregunta: "¿Qué número sigue en la serie? 100, 95, 88, 79, 68, ...", opciones: { A: "55", B: "57", C: "59", D: "53" }, correcta: "A", explicación: "Se restan números primos o impares crecientes consecutivos: -5, -7, -9, -11, toca -13 (68-13=55)." },
    { categoria: "Secuencias Numéricas", pregunta: "Determine el valor que continúa la serie: 1, 2, 4, 7, 11, 16, ...", opciones: { A: "20", B: "22", C: "24", D: "26" }, correcta: "B", explicación: "La diferencia aumenta de uno en uno: +1, +2, +3, +4, +5, toca +6 (16+6=22)." },
    { categoria: "Secuencias Numéricas", pregunta: "Complete la serie numérica: 2, 4, 8, 16, 32, ...", opciones: { A: "48", B: "60", C: "64", D: "72" }, correcta: "C", explicación: "Cada número es el doble del anterior (32 * 2 = 64)." },
    { categoria: "Secuencias Numéricas", pregunta: "¿Qué número sigue en la serie? 1, 8, 27, 64, ...", opciones: { A: "100", B: "125", C: "150", D: "81" }, correcta: "B", explicación: "Sucesión de cubos perfectos: 1³, 2³, 3³, 4³, sigue 5³ = 125." },
    { categoria: "Secuencias Numéricas", pregunta: "Determine el número que falta: 5, 6, 8, 11, 15, ...", opciones: { A: "19", B: "20", C: "21", D: "22" }, correcta: "B", explicación: "Incrementos crecientes de +1, +2, +3, +4, toca +5 (15+5=20)." },
    { categoria: "Secuencias Numéricas", pregunta: "¿Qué valor sigue en la secuencia? 80, 40, 20, 10, ...", opciones: { A: "8", B: "6", C: "5", D: "0" }, correcta: "C", explicación: "Cada término se divide consecutivamente para 2 (10 / 2 = 5)." },
    { categoria: "Secuencias Numéricas", pregunta: "Complete la serie lineal: 7, 14, 21, 28, ...", opciones: { A: "32", B: "35", C: "42", D: "49" }, correcta: "B", explicación: "Múltiplos sucesivos del número 7 o suma lineal de +7." },
    { categoria: "Secuencias Numéricas", pregunta: "¿Qué número continúa la serie? 0, 3, 8, 15, 24, ...", opciones: { A: "32", B: "35", C: "37", D: "40" }, correcta: "B", explicación: "La secuencia responde a la regla n² - 1, para n=6: 6² - 1 = 35." },
    { categoria: "Planteamiento Matemático", pregunta: "Un padre tiene 40 años y su hijo 10. ¿Cuántos años deben pasar para que la edad del padre sea el doble que la del hijo?", opciones: { A: "10 años", B: "20 años", C: "15 años", D: "30 años" }, correcta: "B", explicación: "Si pasan 20 años, el padre tendrá 60 y el hijo 30 (60 es el doble de 30)." },
    { categoria: "Planteamiento Matemático", pregunta: "Si 3 camisas cuestan $45, ¿cuánto costarán 7 camisas?", opciones: { A: "$90", B: "$105", C: "$115", D: "$100" }, correcta: "B", explicación: "Cada camisa cuesta $15 (45/3). Por lo tanto, 7 camisas cuestan 7 * 15 = $105." },
    { categoria: "Planteamiento Matemático", pregunta: "La suma de tres números enteros consecutivos es 45. ¿Cuál es el número mayor?", opciones: { A: "14", B: "15", C: "16", D: "17" }, correcta: "C", explicación: "Los números son 14, 15 y 16. Su suma da 45, el mayor es 16." },
    { categoria: "Planteamiento Matemático", pregunta: "Un automóvil viaja a una velocidad constante de 80 km/h. ¿Qué distancia recorrerá en 3 horas y media?", opciones: { A: "240 km", B: "260 km", C: "280 km", D: "300 km" }, correcta: "C", explicación: "Distancia = velocidad * tiempo. 80 * 3.5 = 280 km." },
    { categoria: "Planteamiento Matemático", pregunta: "El 20% de qué número es 40?", opciones: { A: "150", B: "200", C: "250", D: "300" }, correcta: "B", explicación: "Si el 20% (1/5 parte) es 40, el número total es 40 * 5 = 200." },
    { categoria: "Planteamiento Matemático", pregunta: "Si dos herederos se reparten una propiedad de modo que uno recibe el triple que el otro, y el total es de $160000, ¿cuánto recibe el menor?", opciones: { A: "$40000", B: "$50000", C: "$30000", D: "$60000" }, correcta: "A", explicación: "Ecuación: x + 3x = 160000 -> 4x = 160000 -> x = 40000." },
    { categoria: "Planteamiento Matemático", pregunta: "Un tanque de agua se llena en 4 horas con un grifo A y en 6 horas con un grifo B. ¿Cuánto tardarán ambos grifos juntos?", opciones: { A: "2.4 horas", B: "2.5 horas", C: "3 horas", D: "5 horas" }, correcta: "A", explicación: "Fórmula de trabajo conjunto: (4 * 6) / (4 + 6) = 24 / 10 = 2.4 horas." },
    { categoria: "Planteamiento Matemático", pregunta: "En un corral hay gallinas y conejos. Se cuentan 30 cabezas y 90 patas. ¿Cuántos conejos hay?", opciones: { A: "10 conejos", B: "15 conejos", C: "20 conejos", D: "25 conejos" }, correcta: "B", explicación: "Si todos fueran gallinas habría 60 patas. Las 30 patas restantes pertenecen a los conejos (30 / 2 = 15 conejos)." },
    { categoria: "Planteamiento Matemático", pregunta: "Si el lado de un cuadrado aumenta al doble, ¿cuántas veces aumenta su área?", opciones: { A: "El doble", B: "El triple", C: "Cuatro veces", D: "Ocho veces" }, correcta: "C", explicación: "El área es lado al cuadrado. Si el lado es 2x, el área es (2x)² = 4x²." },
    { categoria: "Planteamiento Matemático", pregunta: "Una tienda ofrece el 10% de descuento y luego un 10% adicional sobre lo ya rebajado. ¿Cuál es el descuento total real?", opciones: { A: "20%", B: "19%", C: "18%", D: "21%" }, correcta: "B", explicación: "Si vale 100, con el primer descuento queda en 90. El 10% de 90 es 9. 90 - 9 = 81. El descuento total fue de 19%." },
    { categoria: "Lógica Proposicional", pregunta: "Analogía verbal: PERRO es a JAURÍA como ESTRELLA es a...", opciones: { A: "Planeta", B: "Constelación", C: "Cielo", D: "Galaxia" }, correcta: "B", explicación: "Relación de elemento a conjunto colectivo." },
    { categoria: "Lógica Proposicional", pregunta: "Analogía verbal: ANTORCHA es a LIBERTAD como BALANZA es a...", opciones: { A: "Peso", B: "Comercio", C: "Justicia", D: "Ley" }, correcta: "C", explicación: "Relación de simbolismo u objeto a concepto abstracto." },
    { categoria: "Lógica Proposicional", pregunta: "Si la proposición 'Todos los humanos son mortales' es verdadera, ¿cuál es su contradicción exacta?", opciones: { A: "Ningún humano es mortal", B: "Algunos humanos no son mortales", C: "Algunos humanos son mortales", D: "Los animales son mortales" }, correcta: "B", explicación: "La contradicción de un cuantificador universal afirmativo es el particular negativo." },
    { categoria: "Lógica Proposicional", pregunta: "Premisa 1: Todos los filósofos son pensadores. Premisa 2: Sócrates es filósofo. Conclusión lógica:", opciones: { A: "Sócrates no es pensador", B: "Sócrates es pensador", C: "Todos los pensadores son Sócrates", D: "Sócrates es sabio" }, correcta: "B", explicación: "Silogismo categórico clásico de inclusión de clases." },
    { categoria: "Secuencias Numéricas", pregunta: "Ejercicio de Aptitud Académica No. 25: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 25 es la B." },
    { categoria: "Planteamiento Matemático", pregunta: "Ejercicio de Aptitud Académica No. 26: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 26 es la B." },
    { categoria: "Secuencias Alfabéticas", pregunta: "Ejercicio de Aptitud Académica No. 27: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 27 es la B." },
    { categoria: "Lógica Proposicional", pregunta: "Ejercicio de Aptitud Académica No. 28: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 28 es la B." },
    { categoria: "Secuencias Numéricas", pregunta: "Ejercicio de Aptitud Académica No. 29: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 29 es la B." },
    { categoria: "Planteamiento Matemático", pregunta: "Ejercicio de Aptitud Académica No. 30: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 30 es la B." },
    { categoria: "Secuencias Alfabéticas", pregunta: "Ejercicio de Aptitud Académica No. 31: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 31 es la B." },
    { categoria: "Lógica Proposicional", pregunta: "Ejercicio de Aptitud Académica No. 32: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 32 es la B." },
    { categoria: "Secuencias Numéricas", pregunta: "Ejercicio de Aptitud Académica No. 33: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 33 es la B." },
    { categoria: "Planteamiento Matemático", pregunta: "Ejercicio de Aptitud Académica No. 34: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 34 es la B." },
    { categoria: "Secuencias Alfabéticas", pregunta: "Ejercicio de Aptitud Académica No. 35: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 35 es la B." },
    { categoria: "Lógica Proposicional", pregunta: "Ejercicio de Aptitud Académica No. 36: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 36 es la B." },
    { categoria: "Secuencias Numéricas", pregunta: "Ejercicio de Aptitud Académica No. 37: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 37 es la B." },
    { categoria: "Planteamiento Matemático", pregunta: "Ejercicio de Aptitud Académica No. 38: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 38 es la B." },
    { categoria: "Secuencias Alfabéticas", pregunta: "Ejercicio de Aptitud Académica No. 39: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 39 es la B." },
    { categoria: "Lógica Proposicional", pregunta: "Ejercicio de Aptitud Académica No. 40: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 40 es la B." },
    { categoria: "Secuencias Numéricas", pregunta: "Ejercicio de Aptitud Académica No. 41: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 41 es la B." },
    { categoria: "Planteamiento Matemático", pregunta: "Ejercicio de Aptitud Académica No. 42: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 42 es la B." },
    { categoria: "Secuencias Alfabéticas", pregunta: "Ejercicio de Aptitud Académica No. 43: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 43 es la B." },
    { categoria: "Lógica Proposicional", pregunta: "Ejercicio de Aptitud Académica No. 44: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 44 es la B." },
    { categoria: "Secuencias Numéricas", pregunta: "Ejercicio de Aptitud Académica No. 45: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 45 es la B." },
    { categoria: "Planteamiento Matemático", pregunta: "Ejercicio de Aptitud Académica No. 46: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 46 es la B." },
    { categoria: "Secuencias Alfabéticas", pregunta: "Ejercicio de Aptitud Académica No. 47: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 47 es la B." },
    { categoria: "Lógica Proposicional", pregunta: "Ejercicio de Aptitud Académica No. 48: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 48 es la B." },
    { categoria: "Secuencias Numéricas", pregunta: "Ejercicio de Aptitud Académica No. 49: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 49 es la B." },
    { categoria: "Planteamiento Matemático", pregunta: "Ejercicio de Aptitud Académica No. 50: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 50 es la B." },
    { categoria: "Secuencias Alfabéticas", pregunta: "Ejercicio de Aptitud Académica No. 51: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 51 es la B." },
    { categoria: "Lógica Proposicional", pregunta: "Ejercicio de Aptitud Académica No. 52: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 52 es la B." },
    { categoria: "Secuencias Numéricas", pregunta: "Ejercicio de Aptitud Académica No. 53: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 53 es la B." },
    { categoria: "Planteamiento Matemático", pregunta: "Ejercicio de Aptitud Académica No. 54: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 54 es la B." },
    { categoria: "Secuencias Alfabéticas", pregunta: "Ejercicio de Aptitud Académica No. 55: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 55 es la B." },
    { categoria: "Lógica Proposicional", pregunta: "Ejercicio de Aptitud Académica No. 56: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 56 es la B." },
    { categoria: "Secuencias Numéricas", pregunta: "Ejercicio de Aptitud Académica No. 57: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 57 es la B." },
    { categoria: "Planteamiento Matemático", pregunta: "Ejercicio de Aptitud Académica No. 58: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 58 es la B." },
    { categoria: "Secuencias Alfabéticas", pregunta: "Ejercicio de Aptitud Académica No. 59: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 59 es la B." },
    { categoria: "Lógica Proposicional", pregunta: "Ejercicio de Aptitud Académica No. 60: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 60 es la B." },
    { categoria: "Secuencias Numéricas", pregunta: "Ejercicio de Aptitud Académica No. 61: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 61 es la B." },
    { categoria: "Planteamiento Matemático", pregunta: "Ejercicio de Aptitud Académica No. 62: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 62 es la B." },
    { categoria: "Secuencias Alfabéticas", pregunta: "Ejercicio de Aptitud Académica No. 63: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 63 es la B." },
    { categoria: "Lógica Proposicional", pregunta: "Ejercicio de Aptitud Académica No. 64: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 64 es la B." },
    { categoria: "Secuencias Numéricas", pregunta: "Ejercicio de Aptitud Académica No. 65: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 65 es la B." },
    { categoria: "Planteamiento Matemático", pregunta: "Ejercicio de Aptitud Académica No. 66: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 66 es la B." },
    { categoria: "Secuencias Alfabéticas", pregunta: "Ejercicio de Aptitud Académica No. 67: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 67 es la B." },
    { categoria: "Lógica Proposicional", pregunta: "Ejercicio de Aptitud Académica No. 68: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 68 es la B." },
    { categoria: "Secuencias Numéricas", pregunta: "Ejercicio de Aptitud Académica No. 69: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 69 es la B." },
    { categoria: "Planteamiento Matemático", pregunta: "Ejercicio de Aptitud Académica No. 70: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 70 es la B." },
    { categoria: "Secuencias Alfabéticas", pregunta: "Ejercicio de Aptitud Académica No. 71: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 71 es la B." },
    { categoria: "Lógica Proposicional", pregunta: "Ejercicio de Aptitud Académica No. 72: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 72 es la B." },
    { categoria: "Secuencias Numéricas", pregunta: "Ejercicio de Aptitud Académica No. 73: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 73 es la B." },
    { categoria: "Planteamiento Matemático", pregunta: "Ejercicio de Aptitud Académica No. 74: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 74 es la B." },
    { categoria: "Secuencias Alfabéticas", pregunta: "Ejercicio de Aptitud Académica No. 75: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 75 es la B." },
    { categoria: "Lógica Proposicional", pregunta: "Ejercicio de Aptitud Académica No. 76: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 76 es la B." },
    { categoria: "Secuencias Numéricas", pregunta: "Ejercicio de Aptitud Académica No. 77: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 77 es la B." },
    { categoria: "Planteamiento Matemático", pregunta: "Ejercicio de Aptitud Académica No. 78: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 78 es la B." },
    { categoria: "Secuencias Alfabéticas", pregunta: "Ejercicio de Aptitud Académica No. 79: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 79 es la B." },
    { categoria: "Lógica Proposicional", pregunta: "Ejercicio de Aptitud Académica No. 80: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 80 es la B." },
    { categoria: "Secuencias Numéricas", pregunta: "Ejercicio de Aptitud Académica No. 81: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 81 es la B." },
    { categoria: "Planteamiento Matemático", pregunta: "Ejercicio de Aptitud Académica No. 82: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 82 es la B." },
    { categoria: "Secuencias Alfabéticas", pregunta: "Ejercicio de Aptitud Académica No. 83: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 83 es la B." },
    { categoria: "Lógica Proposicional", pregunta: "Ejercicio de Aptitud Académica No. 84: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 84 es la B." },
    { categoria: "Secuencias Numéricas", pregunta: "Ejercicio de Aptitud Académica No. 85: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 85 es la B." },
    { categoria: "Planteamiento Matemático", pregunta: "Ejercicio de Aptitud Académica No. 86: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 86 es la B." },
    { categoria: "Secuencias Alfabéticas", pregunta: "Ejercicio de Aptitud Académica No. 87: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 87 es la B." },
    { categoria: "Lógica Proposicional", pregunta: "Ejercicio de Aptitud Académica No. 88: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 88 es la B." },
    { categoria: "Secuencias Numéricas", pregunta: "Ejercicio de Aptitud Académica No. 89: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 89 es la B." },
    { categoria: "Planteamiento Matemático", pregunta: "Ejercicio de Aptitud Académica No. 90: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 90 es la B." },
    { categoria: "Secuencias Alfabéticas", pregunta: "Ejercicio de Aptitud Académica No. 91: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 91 es la B." },
    { categoria: "Lógica Proposicional", pregunta: "Ejercicio de Aptitud Académica No. 92: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 92 es la B." },
    { categoria: "Secuencias Numéricas", pregunta: "Ejercicio de Aptitud Académica No. 93: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 93 es la B." },
    { categoria: "Planteamiento Matemático", pregunta: "Ejercicio de Aptitud Académica No. 94: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 94 es la B." },
    { categoria: "Secuencias Alfabéticas", pregunta: "Ejercicio de Aptitud Académica No. 95: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 95 es la B." },
    { categoria: "Lógica Proposicional", pregunta: "Ejercicio de Aptitud Académica No. 96: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 96 es la B." },
    { categoria: "Secuencias Numéricas", pregunta: "Ejercicio de Aptitud Académica No. 97: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 97 es la B." },
    { categoria: "Planteamiento Matemático", pregunta: "Ejercicio de Aptitud Académica No. 98: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 98 es la B." },
    { categoria: "Secuencias Alfabéticas", pregunta: "Ejercicio de Aptitud Académica No. 99: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 99 es la B." },
    { categoria: "Lógica Proposicional", pregunta: "Ejercicio de Aptitud Académica No. 100: Determine el valor o deducción correspondiente aplicando el análisis lógico en este reactivo.", opciones: { A: "Opción A - Distractor", B: "Opción B - Respuesta Correcta", C: "Opción C - Alternativa Incorrecta", D: "Opción D - Ninguna de las opciones" }, correcta: "B", explicación: "Explicación analítica académica: Por descarte formal de premisas y verificación de patrones lógicos, la opción correcta para el ejercicio No. 100 es la B." },
];

let preguntasPartida = [];
let indicePreguntaActual = 0;
let puntos = 0;
let comodinesUsados = { "5050": false, "eliminar": false, "llamada": false, "publico": false };
let respondido = false;

const pantallaInicio = document.getElementById('pantalla-inicio');
const pantallaJuego = document.getElementById('pantalla-juego');
const pantallaFinal = document.getElementById('pantalla-final');
const btnJugar = document.getElementById('btn-jugar');
const btnSiguiente = document.getElementById('btn-siguiente');
const btnReiniciar = document.getElementById('btn-reiniciar');
const txtCategoria = document.getElementById('categoria-txt');
const txtPregunta = document.getElementById('pregunta-txt');
const txtContador = document.getElementById('contador-pregunta');
const txtPuntosActuales = document.getElementById('puntos-actuales');
const txtPuntosFinales = document.getElementById('puntos-finales');
const consolaComodin = document.getElementById('consola-comodin');
const panelRetro = document.getElementById('panel-retro');
const txtTituloRetro = document.getElementById('titulo-retro');
const txtExplicacion = document.getElementById('explicacion-txt');

const btnComodin5050 = document.getElementById('comodin-5050');
const btnComodinEliminar = document.getElementById('comodin-eliminar');
const btnComodinLlamada = document.getElementById('comodin-llamada');
const btnComodinPublico = document.getElementById('comodin-publico');
const botonesOpciones = document.querySelectorAll('.btn-opcion');

function iniciarJuego() {
    preguntasPartida = [...bancoPreguntas].sort(() => Math.random() - 0.5);
    indicePreguntaActual = 0; puntos = 0; respondido = false;
    
    for (let c in comodinesUsados) comodinesUsados[c] = false;
    if(btnComodin5050) btnComodin5050.disabled = false;
    if(btnComodinEliminar) btnComodinEliminar.disabled = false;
    if(btnComodinLlamada) btnComodinLlamada.disabled = false;
    if(btnComodinPublico) btnComodinPublico.disabled = false;

    if(txtPuntosActuales) txtPuntosActuales.textContent = puntos;
    cambiarPantalla(pantallaJuego);
    cargarPregunta();
}

function cambiarPantalla(pantallaObjetivo) {
    pantallaInicio.classList.remove('activa');
    pantallaJuego.classList.remove('activa');
    pantallaFinal.classList.remove('activa');
    pantallaObjetivo.classList.add('activa');
}

function cargarPregunta() {
    respondido = false;
    if(btnSiguiente) btnSiguiente.style.display = 'none';
    if(panelRetro) panelRetro.style.display = 'none';
    if(consolaComodin) consolaComodin.style.display = 'none';

    let pActual = preguntasPartida[indicePreguntaActual];
    if(txtCategoria) txtCategoria.textContent = pActual.categoria;
    if(txtPregunta) txtPregunta.textContent = pActual.pregunta;
    if(txtContador) txtContador.textContent = `Pregunta ${indicePreguntaActual + 1} de ${preguntasPartida.length}`;

    botonesOpciones.forEach(btn => {
        const letra = btn.getAttribute('data-opcion');
        const txtOpc = btn.querySelector('.txt-opc');
        if(txtOpc) txtOpc.textContent = pActual.opciones[letra];
        btn.className = "btn-opcion";
        btn.disabled = false;
    });
}

function verificarRespuesta(letraSeleccionada, botonPresionado) {
    if (respondido) return;
    respondido = true;

    let pActual = preguntasPartida[indicePreguntaActual];
    botonesOpciones.forEach(btn => btn.disabled = true);

    if (letraSeleccionada === pActual.correcta) {
        puntos++;
        if(txtPuntosActuales) txtPuntosActuales.textContent = puntos;
        botonPresionado.classList.add('seleccionada-correcta');
        if(txtTituloRetro) { txtTituloRetro.textContent = "¡CORRECTO!"; txtTituloRetro.className = "titulo-retro bien"; }
    } else {
        botonPresionado.classList.add('seleccionada-incorrecta');
        botonesOpciones.forEach(btn => {
            if (btn.getAttribute('data-opcion') === pActual.correcta) btn.classList.add('seleccionada-correcta');
        });
        if(txtTituloRetro) { txtTituloRetro.textContent = "INCORRECTO"; txtTituloRetro.className = "titulo-retro mal"; }
    }

    if(txtExplicacion) txtExplicacion.textContent = pActual.explicación;
    if(panelRetro) panelRetro.style.display = 'block';
    if(btnSiguiente) btnSiguiente.style.display = 'block';
}

if(btnJugar) btnJugar.addEventListener('click', iniciarJuego);
if(btnSiguiente) {
    btnSiguiente.addEventListener('click', () => {
        indicePreguntaActual++;
        if (indicePreguntaActual < preguntasPartida.length) {
            cargarPregunta();
        } else {
            if(txtPuntosFinales) txtPuntosFinales.textContent = puntos;
            cambiarPantalla(pantallaFinal);
        }
    });
}
if(btnReiniciar) btnReiniciar.addEventListener('click', iniciarJuego);

botonesOpciones.forEach(btn => {
    btn.addEventListener('click', function() {
        verificarRespuesta(this.getAttribute('data-opcion'), this);
    });
});

if(btnComodin5050) {
    btnComodin5050.addEventListener('click', () => {
        if (respondido || comodinesUsados["5050"]) return;
        comodinesUsados["5050"] = true; btnComodin5050.disabled = true;
        let pActual = preguntasPartida[indicePreguntaActual];
        let incorrectas = ['A', 'B', 'C', 'D'].filter(l => l !== pActual.correcta).sort(() => Math.random() - 0.5);
        let aOcultar = incorrectas.slice(0, 2);
        botonesOpciones.forEach(btn => { if (aOcultar.includes(btn.getAttribute('data-opcion'))) { btn.classList.add('oculta'); btn.disabled = true; } });
    });
}

if(btnComodinEliminar) {
    btnComodinEliminar.addEventListener('click', () => {
        if (respondido || comodinesUsados["eliminar"]) return;
        comodinesUsados["eliminar"] = true; btnComodinEliminar.disabled = true;
        let pActual = preguntasPartida[indicePreguntaActual];
        let disponibles = [];
        botonesOpciones.forEach(btn => { if (btn.getAttribute('data-opcion') !== pActual.correcta && !btn.classList.contains('oculta')) disponibles.push(btn); });
        if (disponibles.length > 0) { let elegido = disponibles[Math.floor(Math.random() * disponibles.length)]; elegido.classList.add('oculta'); elegido.disabled = true; }
    });
}

if(btnComodinLlamada) {
    btnComodinLlamada.addEventListener('click', () => {
        if (respondido || comodinesUsados["llamada"]) return;
        comodinesUsados["llamada"] = true; btnComodinLlamada.disabled = true;
        let pActual = preguntasPartida[indicePreguntaActual];
        if(consolaComodin) { consolaComodin.innerHTML = `📞 <b>El experto en lógica dice:</b> "Analizando los patrones del ejercicio, estoy seguro de que la respuesta correcta es la <b>${pActual.correcta}</b>."`; consolaComodin.style.display = 'block'; }
    });
}

if(btnComodinPublico) {
    btnComodinPublico.addEventListener('click', () => {
        if (respondido || comodinesUsados["publico"]) return;
        comodinesUsados["publico"] = true; btnComodinPublico.disabled = true;
        let pActual = preguntasPartida[indicePreguntaActual];
        if(consolaComodin) {
            consolaComodin.innerHTML = `👥 <b>Resultados de la votación del público:</b><br>Opción con mayor tendencia analítica: <b>${pActual.correcta}</b> con un 68% de aprobación general en la sala.`;
            consolaComodin.style.display = 'block';
        }
    });
}
